# Generated by Django 3.0.3 on 2020-06-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloggin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Age', models.IntegerField()),
                ('Blog', models.TextField()),
                ('Blog_Image', models.ImageField(upload_to='blog_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Blog_Image',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Name',
        ),
    ]
