# Generated by Django 3.0.3 on 2020-06-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloggin', '0002_auto_20200602_0610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Age',
            field=models.CharField(default='SOME STRING', max_length=256),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Blog',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Blog_Image',
            field=models.ImageField(default='SOME STRING', upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Name',
            field=models.CharField(default='SOME STRING', max_length=256),
        ),
    ]
