# Generated by Django 3.0.3 on 2020-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloggin', '0003_auto_20200602_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Blog_Image',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='SOME STRING', upload_to='profile_pic'),
        ),
    ]
