# Generated by Django 3.0.3 on 2020-06-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bloggin', '0004_auto_20200602_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Name',
        ),
    ]
